{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2017-18265",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugs.debian.org/875829",
          "name": "https://bugs.debian.org/875829",
          "refsource": "MISC"
        },
        {
          "url": "https://hg.prosody.im/0.9/rev/176b7f4e4ac9",
          "name": "https://hg.prosody.im/0.9/rev/176b7f4e4ac9",
          "refsource": "MISC"
        },
        {
          "url": "https://hg.prosody.im/0.9/rev/adfffc5b4e2a",
          "name": "https://hg.prosody.im/0.9/rev/adfffc5b4e2a",
          "refsource": "MISC"
        },
        {
          "url": "https://prosody.im/issues/issue/987",
          "name": "https://prosody.im/issues/issue/987",
          "refsource": "MISC"
        },
        {
          "url": "https://www.debian.org/security/2018/dsa-4198",
          "name": "DSA-4198",
          "refsource": "DEBIAN"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Prosody before 0.10.0 allows remote attackers to cause a denial of service (application crash), related to an incompatibility with certain versions of the LuaSocket library, such as the lua-socket package from Debian stretch. The attacker needs to trigger a stream error. A crash can be observed in, for example, the c2s module."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-05-09T17:29Z",
  "lastModifiedDate": "2018-05-12T01:29Z"
}