{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-1000178",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/quassel/quassel/blob/master/src/common/protocols/datastream/datastreampeer.cpp#L62",
          "name": "https://github.com/quassel/quassel/blob/master/src/common/protocols/datastream/datastreampeer.cpp#L62",
          "refsource": "CONFIRM"
        },
        {
          "url": "https://i.imgur.com/JJ4QcNq.png",
          "name": "https://i.imgur.com/JJ4QcNq.png",
          "refsource": "MISC"
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2018/05/msg00001.html",
          "name": "[debian-lts-announce] 20180504 [SECURITY] [DLA 1370-1] quassel security update",
          "refsource": "MLIST"
        },
        {
          "url": "https://www.debian.org/security/2018/dsa-4189",
          "name": "DSA-4189",
          "refsource": "DEBIAN"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A heap corruption of type CWE-120 exists in quassel version 0.12.4 in quasselcore in void DataStreamPeer::processMessage(const QByteArray &msg) datastreampeer.cpp line 62 that allows an attacker to execute code remotely."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-05-08T15:29Z",
  "lastModifiedDate": "2018-05-10T01:29Z"
}